### ISSUE TITLE
For multiple emotion

### ISSUE THREAD

**Issue by rishikksh20** [nik0spapp/usent#1]
What about emotions like sad, happy, angry, fulfill etc not just positive and negative

**Comment by nik0spapp** [comment]
Hello, emotions are not supported by this library. You could take a look at our other library: https://github.com/idiap/emorec  which contains target classes such as unconvincing, persuasive, fascinating, funny etc. (which are more nuanced than sad, happy and angry classes).  

Hope it helps.

**Comment by rishikksh20** [comment]
Thanks
